db:
  path: ./data
telegram:
  api_id: 1264606
  api_hash: 2ba94108cf606b3910bc9c6d476980c2
  account:
    session_file: ~/.tgfs/account.session
  bot:
    token: 6081157716:AAE3PyPfN7zoBdyK4qo1wb2XpyfnbIOyoD4
    session_file: ~/.tgfs/bot.session
  login_timeout: 300000
  private_file_channel: 2047163427
  public_file_channel: 0

tgfs:
  users:
    fatshotty:
      password: fatsh0tty
      admin: true
    user:
      password: password
      admin: false
  download:
    chunk_size_kb: 5120

webdav:
  host: 0.0.0.0
  port: 1900
  path: /

manager:
  host: 0.0.0.0
  port: 1901
  path: /
  bot:
    token: 6081157716:AAE3PyPfN7zoBdyK4qo1wb2XpyfnbIOyoD4
    chat_id: 63212494
